name: First_Workflow

on:
    push:
        branches:
            - main

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: list folders
              run: ls -l

    job2:
        runs-on: ubuntu-latest
        steps:
            - run: ls -l

    job3:
        runs-on: ubuntu-latest
        steps:
            - name: create folder 
              run: mkdir folder1

            - run: pwd

            - name: list folders
              run: ls -l